### ISSUE TITLE
config: Don't reference internal PHP classes

### ISSUE THREAD

**Issue by lazka** [digital-blueprint/relay-mono-bundle#21]
Instead of

```yaml
  payment_types:
    tuition_fee:
      service: 'Dbp\Relay\MonoConnectorCampusonlineBundle\Service\TuitionFeeService'
```

```yaml
  payment_types:
    tuition_fee:
      provider: 'tuition_fee_provider'
```

where `tuition_fee_provider` is defined in the CO bundle config.

This way we don't expose PHP stuff to the config, which means we can change it later on, and is less confusing to the integrator.
